"""Giphy API service for searching GIFs."""

import httpx
from config import get_settings
from models import GifResult

GIPHY_SEARCH_URL = "https://api.giphy.com/v1/gifs/search"


async def search_gifs(query: str, limit: int = 20) -> list[GifResult]:
    """
    Search Giphy for GIFs matching the query.
    
    Args:
        query: The search term (generated by the vision model).
        limit: Maximum number of results to return.
    
    Returns:
        List of GifResult objects.
    """
    settings = get_settings()

    params = {
        "api_key": settings.giphy_api_key,
        "q": query,
        "limit": limit,
        "rating": "pg",
        "lang": "en",
    }

    async with httpx.AsyncClient() as client:
        response = await client.get(GIPHY_SEARCH_URL, params=params, timeout=10.0)
        response.raise_for_status()
        data = response.json()

    results = []
    for gif in data.get("data", []):
        images = gif.get("images", {})

        # Get the best quality URL and a smaller preview
        original = images.get("original", {})
        fixed_width = images.get("fixed_width", {})

        results.append(
            GifResult(
                id=gif.get("id", ""),
                url=original.get("url", ""),
                preview_url=fixed_width.get("url", original.get("url", "")),
                title=gif.get("title", "Untitled GIF"),
                source="giphy",
            )
        )

    return results
